const crypto = require('crypto');
const { parse, Kind, graphql: executeGraphQL } = require('graphql');
const yaml = require('js-yaml');
const { faker } = require('@faker-js/faker');
const { addMocksToSchema } = require('@graphql-tools/mock');
const { makeExecutableSchema } = require('@graphql-tools/schema');
const { SCALAR_TYPES, unwrapGqlType } = require('./graphql-utils.cjs');
const { generateMockValue, generateMockObject } = require('./mock-generators.cjs');
const { buildFieldsForType } = require('./postman-builder.cjs');
const { isValidJSON } = require('./schema-loader.cjs');

function detectSchemaType(schema) {
  if (!schema) return 'unknown';

  const s = schema.trim();

  // AsyncAPI (check before OpenAPI since both can be YAML/JSON)
  if (s.includes('asyncapi') || s.includes('"asyncapi"')) return 'asyncapi';

  // gRPC / Protocol Buffers
  if (/syntax\s*=\s*"proto[23]"/.test(s) || /\bservice\s+\w+\s*\{[\s\S]*?\brpc\s+/.test(s)) return 'grpc';

  // OpenAPI (check first, before generic JSON)
  if (s.includes('openapi') || s.includes('paths:') || s.includes('"openapi"') || s.includes('"paths"')) return 'openapi';

  // GraphQL SDL (type Query, type Mutation, type SomeName {, etc.)
  if (s.includes('type ') || s.includes('Query') || s.includes('query ')) return 'graphql';

  // Plain type definitions: { name: String, age: Int } or key: type format
  // Be lenient - if it looks like JSON or key-value pairs, try to convert it
  if (s.startsWith('{') || s.includes(':')) {
    try {
      const result = detectAndConvertPlainType(s, 'AutoGenerated');
      if (result) {
        console.log('✓ Detected plain-types from:', s.substring(0, 50));
        return 'plain-types';
      }
    } catch (e) { 
      console.log('⚠️ detectAndConvertPlainType error (will try json):', e.message);
    }
  }

  // Valid JSON that's not a schema/type definition
  if (isValidJSON(s)) return 'json';

  return 'unknown';
}

function parseGraphQLSchema(schemaText) {
  const doc = parse(schemaText);
  const types = {};
  const operations = [];

  for (const def of doc.definitions) {
    const isTypelike = def.kind === Kind.OBJECT_TYPE_DEFINITION || def.kind === Kind.OBJECT_TYPE_EXTENSION
      || def.kind === 'InterfaceTypeDefinition' || def.kind === 'InterfaceTypeExtension';

    if (isTypelike) {
      const typeName = def.name.value;
      if (!types[typeName]) types[typeName] = {};
      for (const field of (def.fields || [])) {
        types[typeName][field.name.value] = unwrapGqlType(field.type);
      }

      if (typeName === 'Query' || typeName === 'Mutation') {
        for (const field of (def.fields || [])) {
          const retType = unwrapGqlType(field.type);
          const args = (field.arguments || []).map(a => ({
            name: a.name.value,
            type: unwrapGqlType(a.type),
          }));
          operations.push({
            name: field.name.value,
            method: typeName === 'Query' ? 'QUERY' : 'MUTATION',
            returnType: retType.name,
            isList: retType.isList,
            args,
          });
        }
      }
    }

    if (def.kind === 'UnionTypeDefinition') {
      const typeName = def.name.value;
      if (!types[typeName]) types[typeName] = {};
    }
  }

  // Merge implementing types' fields into interfaces/unions so the full
  // field set is available for query building and LLM prompts
  for (const def of doc.definitions) {
    if ((def.kind === Kind.OBJECT_TYPE_DEFINITION || def.kind === Kind.OBJECT_TYPE_EXTENSION) && def.interfaces) {
      for (const iface of def.interfaces) {
        const ifaceName = iface.name.value;
        if (types[ifaceName] && def.fields) {
          for (const field of def.fields) {
            if (!types[ifaceName][field.name.value]) {
              types[ifaceName][field.name.value] = unwrapGqlType(field.type);
            }
          }
        }
      }
    }
  }

  // For union types, merge fields from member types
  for (const def of doc.definitions) {
    if (def.kind === 'UnionTypeDefinition' && def.types) {
      const unionName = def.name.value;
      if (!types[unionName]) types[unionName] = {};
      for (const memberRef of def.types) {
        const memberFields = types[memberRef.name.value];
        if (memberFields) {
          for (const [fname, ftype] of Object.entries(memberFields)) {
            if (!types[unionName][fname]) types[unionName][fname] = ftype;
          }
        }
      }
    }
  }

  // Extract enum values
  const enums = {};
  for (const def of doc.definitions) {
    if (def.kind === 'EnumTypeDefinition') {
      enums[def.name.value] = (def.values || []).map(v => v.name.value);
    }
  }

  const scalars = new Set();
  const inputs = {};
  for (const def of doc.definitions) {
    if (def.kind === 'ScalarTypeDefinition') {
      scalars.add(def.name.value);
    }
    if (def.kind === 'InputObjectTypeDefinition') {
      inputs[def.name.value] = {};
      for (const field of (def.fields || [])) {
        inputs[def.name.value][field.name.value] = unwrapGqlType(field.type);
      }
    }
  }

  return { types, operations, enums, scalars, inputs };
}

function validateGraphQLSchema(schemaText) {
  const warnings = [];
  const errors = [];

  try {
    const { types, enums, operations, scalars, inputs } = parseGraphQLSchema(schemaText);
    
    const builtInScalars = new Set(['String', 'Int', 'Float', 'Boolean', 'ID']);
    const definedTypes = new Set([...Object.keys(types), ...Object.keys(enums), ...Object.keys(inputs), ...scalars, ...builtInScalars]);

    // Check all field type references
    for (const [typeName, fields] of Object.entries(types)) {
      for (const [fieldName, fieldType] of Object.entries(fields)) {
        // fieldType is { name, isList, isRequired, isNonNullList }
        const baseType = fieldType.name;
        
        if (!definedTypes.has(baseType)) {
          errors.push({
            type: 'UNDEFINED_TYPE',
            message: `Field '${typeName}.${fieldName}' references undefined type '${baseType}'`,
            field: `${typeName}.${fieldName}`,
            referencedType: baseType,
            available: Array.from(definedTypes).sort(),
          });
        }
      }
    }

    // Check operation return types
    for (const op of operations) {
      if (!definedTypes.has(op.returnType)) {
        errors.push({
          type: 'UNDEFINED_OPERATION_RETURN',
          message: `Operation '${op.name}' returns undefined type '${op.returnType}'`,
          operation: op.name,
          returnType: op.returnType,
          available: Array.from(definedTypes).sort(),
        });
      }

      // Check argument types
      for (const arg of op.args) {
        if (!definedTypes.has(arg.type.name)) {
          warnings.push({
            type: 'UNDEFINED_ARGUMENT_TYPE',
            message: `Operation '${op.name}' argument '${arg.name}' has undefined type '${arg.type.name}'`,
            operation: op.name,
            argument: arg.name,
            argumentType: arg.type.name,
          });
        }
      }
    }

    // Check for empty or minimal schema
    if (Object.keys(types).length === 0 && Object.keys(enums).length === 0) {
      warnings.push({
        type: 'EMPTY_SCHEMA',
        message: 'Schema contains no types or enums',
      });
    }

    // Check for Query type existence
    if (!types.Query && !types.Mutation && !types.Subscription) {
      errors.push({
        type: 'NO_ROOT_TYPE',
        message: 'Schema must define at least one of: Query, Mutation, or Subscription',
      });
    }

    return {
      valid: errors.length === 0,
      errors,
      warnings,
      summary: {
        typeCount: Object.keys(types).length,
        enumCount: Object.keys(enums).length,
        operationCount: operations.length,
        errorCount: errors.length,
        warningCount: warnings.length,
      },
    };
  } catch (e) {
    const parseErrors = [{
      type: 'PARSE_ERROR',
      message: `Failed to parse schema: ${e.message}`,
    }];
    return {
      valid: false,
      errors: parseErrors,
      warnings: [],
      summary: {
        typeCount: 0,
        enumCount: 0,
        operationCount: 0,
        errorCount: parseErrors.length,
        warningCount: 0,
      },
    };
  }
}

function cleanSchemaForMocking(schemaText) {
  let s = schemaText;

  s = s.replace(/^#\s*microcksId:.*$/m, '');

  s = s.replace(/extend\s+schema[\s\S]*?(?=\n(?:directive|type|enum|union|interface|input|scalar)\b)/m, '');
  s = s.replace(/^schema\s+@link[\s\S]*?\}\s*/m, '');

  const fedNames = 'key|external|requires|provides|extends|inaccessible|shareable|override|tag|link|cacheControl';

  s = s.replace(new RegExp('directive\\s+@(?:' + fedNames + ')\\s*\\([\\s\\S]*?\\)\\s*(?:repeatable\\s+)?on\\s+[A-Z_|\\s]+', 'g'), '');
  s = s.replace(new RegExp('directive\\s+@(?:' + fedNames + ')\\s+(?:repeatable\\s+)?on\\s+[A-Z_|\\s]+', 'g'), '');

  function stripDirectiveUsage(text) {
    let result = '';
    let i = 0;
    while (i < text.length) {
      const atIdx = text.indexOf('@', i);
      if (atIdx === -1) { result += text.slice(i); break; }
      result += text.slice(i, atIdx);
      const rest = text.slice(atIdx);
      const nameMatch = rest.match(new RegExp('^@(?:' + fedNames + ')(?=\\s|\\(|$)'));
      if (!nameMatch) { result += '@'; i = atIdx + 1; continue; }
      let j = nameMatch[0].length;
      let afterName = rest.slice(j);
      const parenStart = afterName.search(/\S/);
      if (parenStart >= 0 && afterName[parenStart] === '(') {
        j += parenStart + 1;
        let depth = 1;
        let inStr = false;
        let pos = j;
        while (pos < rest.length && depth > 0) {
          const ch = rest[pos];
          if (inStr) { if (ch === '"' && rest[pos - 1] !== '\\\\') inStr = false; }
          else if (ch === '"') inStr = true;
          else if (ch === '(') depth++;
          else if (ch === ')') depth--;
          pos++;
        }
        j = pos;
      }
      i = atIdx + j;
    }
    return result;
  }

  s = stripDirectiveUsage(s);

  s = s.replace(/^\s*scalar\s+_FieldSet\b.*$/gm, '');
  s = s.replace(/^\s*scalar\s+_Any\b.*$/gm, '');

  s = s.replace(/^extend\s+type\b/gm, 'type');

  const customScalars = new Set();
  const builtins = new Set(['String', 'Int', 'Float', 'Boolean', 'ID', 'Query', 'Mutation', 'Subscription']);
  const scalarRe = /(?::\s*\[?\s*)(\w+)/g;
  let m;
  while ((m = scalarRe.exec(s)) !== null) {
    if (SCALAR_TYPES.has(m[1]) && !builtins.has(m[1])) customScalars.add(m[1]);
  }

  const existingScalars = new Set();
  const existingRe = /^\s*scalar\s+(\w+)/gm;
  while ((m = existingRe.exec(s)) !== null) existingScalars.add(m[1]);

  let scalarBlock = '';
  for (const sc of customScalars) {
    if (!existingScalars.has(sc)) scalarBlock += `scalar ${sc}\n`;
  }

  if (!s.includes('enum CacheControlScope')) {
    s = s.replace(/\bCacheControlScope\b/g, 'String');
  }

  s = s.replace(/\n{3,}/g, '\n\n');

  return scalarBlock + s;
}

async function generateMockViaGraphQLTools(schemaText, ops, types, samplesPerOp) {
  const cleaned = cleanSchemaForMocking(schemaText);
  const schema = makeExecutableSchema({ typeDefs: cleaned });

  const { types: parsedTypes, enums: parsedEnums } = parseGraphQLSchema(schemaText);

  const mocks = {
    Date: () => faker.date.recent().toISOString().split('T')[0],
    DateTime: () => faker.date.recent().toISOString(),
    JSON: () => ({ key: 'value' }),
    Long: () => Math.floor(Math.random() * 1000000),
    BigDecimal: () => +(Math.random() * 1000).toFixed(2),
    URL: () => 'https://example.com/' + faker.lorem.slug(),
    URI: () => 'https://example.com/' + faker.lorem.slug(),
    _FieldSet: () => 'id',
    _Any: () => ({ __typename: 'Mock', id: '1' }),
    ID: () => crypto.randomUUID(),
    Int: () => faker.number.int({ min: 0, max: 1000 }),
    Float: () => +(Math.random() * 100).toFixed(2),
    Boolean: () => Math.random() > 0.5,
    String: () => faker.lorem.words(2),
  };

  for (const [typeName, fields] of Object.entries(parsedTypes)) {
    if (typeName === 'Query' || typeName === 'Mutation' || typeName === 'Subscription') continue;
    const scalarFields = {};
    for (const [fieldName, typeInfo] of Object.entries(fields)) {
      if (SCALAR_TYPES.has(typeInfo.name) || parsedEnums[typeInfo.name]) {
        scalarFields[fieldName] = typeInfo;
      }
    }
    if (Object.keys(scalarFields).length > 0) {
      mocks[typeName] = () => {
        const obj = {};
        for (const [fieldName, typeInfo] of Object.entries(scalarFields)) {
          obj[fieldName] = generateMockValue(fieldName, typeInfo, parsedTypes, parsedEnums, 3);
        }
        return obj;
      };
    }
  }

  const mockedSchema = addMocksToSchema({ schema, mocks });
  const results = {};

  function dummyArgValue(argType, depth = 0) {
    const t = argType.name;
    if (t === 'String') return '"mock"';
    if (t === 'Int') return '1';
    if (t === 'Float' || t === 'BigDecimal') return '1.0';
    if (t === 'Boolean') return 'true';
    if (t === 'ID') return '"mock-id"';
    if (parsedEnums[t]) return parsedEnums[t][0];
    if (types[t] && depth < 2) {
      const fields = types[t];
      const parts = Object.entries(fields).map(([fname, ftype]) => {
        const v = ftype.isList ? `[${dummyArgValue(ftype, depth + 1)}]` : dummyArgValue(ftype, depth + 1);
        return `${fname}: ${v}`;
      });
      return `{${parts.join(', ')}}`;
    }
    return '"mock"';
  }

  for (const op of ops) {
    const fieldSelection = buildFieldsForType(types, op.returnType, 0);
    if (!fieldSelection) continue;

    let argStr = '';
    if (op.args && op.args.length > 0) {
      const argParts = op.args.map(a => {
        const val = a.type.isList ? `[${dummyArgValue(a.type)}]` : dummyArgValue(a.type);
        return `${a.name}: ${val}`;
      });
      argStr = `(${argParts.join(', ')})`;
    }

    const keyword = op.method === 'MUTATION' ? 'mutation' : 'query';
    const queryStr = `${keyword} { ${op.name}${argStr} { ${fieldSelection} } }`;

    const examples = [];
    for (let i = 0; i < samplesPerOp; i++) {
      const result = await executeGraphQL({ schema: mockedSchema, source: queryStr });
      if (result.data && result.data[op.name] != null) {
        examples.push(result.data[op.name]);
      }
    }
    if (examples.length > 0) results[op.name] = examples;
  }

  return results;
}

function parseOpenAPISpec(specText) {
  let spec;
  try {
    spec = JSON.parse(specText);
  } catch (_) {
    spec = yaml.load(specText);
  }
  if (!spec || !spec.paths) throw new Error('Invalid OpenAPI spec: no paths found');

  const serviceName = spec.info?.title || 'RESTService';
  const serviceVersion = spec.info?.version || '1.0';
  const operations = [];

  for (const [pathKey, methods] of Object.entries(spec.paths)) {
    for (const [method, opDef] of Object.entries(methods)) {
      if (['get', 'post', 'put', 'patch', 'delete'].indexOf(method) === -1) continue;
      const opName = `${method.toUpperCase()} ${pathKey}`;
      const successCode = Object.keys(opDef.responses || {}).find(c => c.startsWith('2')) || '200';
      const successResp = (opDef.responses || {})[successCode] || {};
      const contentType = successResp.content ? Object.keys(successResp.content)[0] : 'application/json';
      const respSchema = successResp.content?.[contentType]?.schema || {};

      const reqBody = opDef.requestBody?.content?.['application/json']?.schema || null;

      operations.push({
        name: opName,
        operationId: opDef.operationId || opName,
        method: method.toUpperCase(),
        path: pathKey,
        responseCode: parseInt(successCode),
        responseSchema: respSchema,
        requestSchema: reqBody,
        parameters: opDef.parameters || [],
        summary: opDef.summary || '',
      });
    }
  }
  return { spec, serviceName, serviceVersion, operations };
}

function resolveSchemaRef(ref, spec) {
  if (!ref || !ref.startsWith('#/')) return {};
  const parts = ref.replace('#/', '').split('/');
  let result = spec;
  for (const p of parts) { result = result?.[p]; }
  return result || {};
}

function describeSchema(schema, spec, depth = 0, indent = '') {
  if (depth > 6) return '...';
  if (!schema) return 'any';
  if (schema.$ref) schema = resolveSchemaRef(schema.$ref, spec);
  if (!schema) return 'any';

  if (schema.enum) {
    return `enum(${schema.enum.slice(0, 5).join('|')}${schema.enum.length > 5 ? '|...' : ''})`;
  }

  const typeStr = (s) => {
    let t = s.type || 'any';
    if (s.format) t += `(${s.format})`;
    return t;
  };

  if (schema.type === 'object' || schema.properties) {
    const inner = indent + '  ';
    const fields = Object.entries(schema.properties || {}).map(([k, v]) => {
      if (v.$ref) v = resolveSchemaRef(v.$ref, spec);
      if (!v) return `${inner}${k}: any`;
      if (v.type === 'object' || v.properties) {
        return `${inner}${k}: ${describeSchema(v, spec, depth + 1, inner)}`;
      }
      if (v.type === 'array' && v.items) {
        let items = v.items.$ref ? resolveSchemaRef(v.items.$ref, spec) : v.items;
        if (items && (items.type === 'object' || items.properties)) {
          return `${inner}${k}: [${describeSchema(items, spec, depth + 1, inner)}]`;
        }
        return `${inner}${k}: ${typeStr(items || {})}[]`;
      }
      if (v.enum) return `${inner}${k}: ${describeSchema(v, spec, depth + 1, inner)}`;
      return `${inner}${k}: ${typeStr(v)}`;
    });
    return `{\n${fields.join(',\n')}\n${indent}}`;
  }

  if (schema.type === 'array' && schema.items) {
    let items = schema.items.$ref ? resolveSchemaRef(schema.items.$ref, spec) : schema.items;
    if (items && (items.type === 'object' || items.properties)) {
      return `[${describeSchema(items, spec, depth + 1, indent)}]`;
    }
    return `${typeStr(items || {})}[]`;
  }

  return typeStr(schema);
}

const FAILURE_SCENARIOS = {
  'success': { name: 'Success (Happy Path)', prompt: 'Generate correct, realistic data with ALL fields present, proper types, and realistic values. This should be a perfect, valid API response with no issues — realistic names, valid dates, proper nested structures, and all arrays populated with 1-2 items.' },
  'wrong-types': { name: 'Wrong Data Types', prompt: 'Generate data where field values have WRONG types: strings where numbers expected, numbers where strings expected, objects where arrays expected. Make it look like a provider API regression.' },
  'missing-fields': { name: 'Missing Required Fields', prompt: 'Generate data with several important fields completely missing (not null, but absent from the JSON). Simulate a provider removing fields in a breaking change.' },
  'null-values': { name: 'Unexpected Nulls', prompt: 'Generate data where fields that should have values are null. Simulate a database issue or incomplete data load.' },
  'empty-arrays': { name: 'Empty Collections', prompt: 'Generate data where all array/list fields are empty []. Simulate an upstream data source returning no items.' },
  'malformed-dates': { name: 'Malformed Dates', prompt: 'Generate data where date/time fields have wrong formats: Unix timestamps instead of ISO strings, "N/A", epoch 0, or invalid strings like "not-a-date".' },
  'deprecated-fields': { name: 'Deprecated Field Changes', prompt: 'Generate data where deprecated fields are removed and replaced with new unexpected field names. Simulate an API migration the consumer was not notified about.' },
  'extra-fields': { name: 'Extra Unknown Fields', prompt: 'Generate valid data but add many extra unexpected fields that the consumer schema does not define. Simulate a provider adding new fields.' },
  'encoding-issues': { name: 'Encoding/Special Chars', prompt: 'Generate data with special characters, unicode, HTML entities, and XSS payloads in string fields. Test consumer input sanitization.' },
  'boundary-values': { name: 'Boundary Values', prompt: 'Generate data with extreme values: very long strings (500+ chars), negative numbers, zero, MAX_INT, empty strings, single character strings.' },
  'partial-response': { name: 'Partial/Truncated', prompt: 'Generate data that looks like a truncated API response — some objects missing, arrays with only 1 item, strings cut off mid-sentence.' },
  'mixed-good-bad': { name: 'Mixed Good & Bad', prompt: 'Generate data where SOME fields have correct, realistic values and OTHER fields have wrong types, null values, or are missing. Mix it up — roughly half the fields should be correct and half should be broken. This simulates a partial API regression where only some fields are affected.' },
};

function parseSamplesFromPrompt(prompt) {
  if (!prompt) return { total: 1, scenarioInstructions: '' };

  // Try, in order: "generate N ..." (most common phrasing), then a number
  // immediately followed by a plausible noun, then any number in the prompt
  // at all. The old version only matched a fixed word list (sample/example/
  // mock/...) right after the digit, so "Generate 5 realistic products…"
  // silently fell back to 1 because "realistic" wasn't in that list.
  const numMatch =
    prompt.match(/generate\s+(\d+)/i) ||
    prompt.match(/(\d+)\s*(?:different|sample|example|mock|value|scenario|response|record|item|entry|entries|row|object|product|user|post|order|customer|account)/i) ||
    prompt.match(/(\d+)/);
  const total = numMatch ? Math.max(1, parseInt(numMatch[1])) : 1;

  const scenarioNames = Object.keys(FAILURE_SCENARIOS);
  const mentionedScenarios = scenarioNames.filter(s =>
    prompt.toLowerCase().includes(s.replace(/-/g, ' ')) || prompt.toLowerCase().includes(s)
  );

  const hasSuccess = /success|happy|valid|correct|good/i.test(prompt);
  const hasMix = /mix|combin|variety|different\s*scenario|failure|error|bad/i.test(prompt);

  let scenarioInstructions = '';
  if (mentionedScenarios.length > 0 || hasMix) {
    if (mentionedScenarios.length > 0 && hasSuccess) {
      const successCount = Math.max(1, Math.floor(total / 2));
      const failCount = total - successCount;
      const perScenario = Math.max(1, Math.floor(failCount / mentionedScenarios.length));
      scenarioInstructions = `\n\nSCENARIO MIX REQUIRED:\nGenerate ${successCount} success/happy-path examples with fully correct data.\nThen generate ${failCount} failure examples split across: ${mentionedScenarios.join(', ')} (${perScenario} each).\nLabel each example by prefixing a "_scenario" field with its type (e.g. "_scenario": "success", "_scenario": "wrong-types").`;
    } else if (mentionedScenarios.length > 0) {
      const perScenario = Math.max(1, Math.floor(total / mentionedScenarios.length));
      scenarioInstructions = `\n\nSCENARIO MIX REQUIRED:\nGenerate examples split across: ${mentionedScenarios.join(', ')} (${perScenario} each).\nLabel each with a "_scenario" field.`;
    } else if (hasMix) {
      const successCount = Math.max(1, Math.floor(total / 3));
      const failCount = total - successCount;
      scenarioInstructions = `\n\nSCENARIO MIX REQUIRED:\nGenerate ${successCount} success examples with correct data, and ${failCount} failure examples using a variety of failure scenarios: wrong-types, missing-fields, null-values, empty-arrays, boundary-values, mixed-good-bad.\nLabel each with a "_scenario" field (e.g. "_scenario": "success", "_scenario": "wrong-types").`;
    }
  }

  return { total, scenarioInstructions };
}

async function enhanceSchemaWithAI(schema, prompt) {
  // plug your existing AI call here
  return schema; // fallback (no-op for now)
}

function detectAndConvertPlainType(input, fallbackServiceName) {
  try {
    const trimmed = input.trim();

    // Pattern 1: Simple "key: type" lines (e.g. "name: string\nage: INT")
    const simpleLines = trimmed.split('\n').map(l => l.trim()).filter(l => l && !l.startsWith('#') && !l.startsWith('//'));
    const simpleKV = /^(\w+)\s*:\s*(string|int|integer|float|number|boolean|bool|date|datetime|id|uuid)$/i;
    const isSimpleKV = simpleLines.length > 0 && simpleLines.every(l => simpleKV.test(l));

    // Pattern 2: JSON object - flat type values OR nested structures
    let jsonObj = null;
    let isNestedJSON = false;
    if (trimmed.startsWith('{') && !/"openapi"|"swagger"|"paths"|"type"\s*:\s*"object"/.test(trimmed)) {
      try {
        // Try direct JSON parse first
        const parsed = JSON.parse(trimmed);
        const vals = Object.values(parsed);
        if (vals.length > 0) {
          // Check if it's simple flat type definitions (all strings matching type names)
          const isFlat = vals.every(v => typeof v === 'string' && /^(string|int|integer|float|number|boolean|bool|date|datetime|id|uuid)$/i.test(v));
          console.log('📦 Pattern 2 JSON parsed successfully - isFlat:', isFlat, 'vals:', vals);
          if (isFlat) {
            jsonObj = parsed;
          } else {
            // Otherwise, treat it as nested JSON structure (actual data shape)
            jsonObj = parsed;
            isNestedJSON = true;
          }
        }
      } catch (e) {
        console.log('⚠️ Pattern 2 JSON parse failed, trying lenient:', e.message.substring(0, 50));
        // Try lenient parsing: handle both { name: String } and { "name": String } formats
        // 1. Remove ALL whitespace including Unicode line/paragraph separators
        let normalized = trimmed
          .replace(/[\n\r\u2028\u2029\s]/g, '') // Remove all whitespace including Unicode separators
          .replace(/([{,])/g, '$1 ') // Add space after { and ,
          .trim();
        // 2. Remove spaces around colons: "name" : "String" → "name":"String"
        normalized = normalized.replace(/\s*:\s*/g, ':');
        // 3. Quote unquoted keys: {name: or ,name: → {"name": or ,"name":
        normalized = normalized.replace(/([{,])([a-zA-Z_]\w*):/g, '$1"$2":');
        // 4. Quote unquoted type values: :String, or :String} → :"String", or :"String"}
        normalized = normalized.replace(/:([a-zA-Z_]\w*)([,}])/g, ':"$1"$2');
        console.log('Lenient normalized:', normalized);
        try {
          const parsed = JSON.parse(normalized);
          const vals = Object.values(parsed);
          console.log('📦 Lenient parse succeeded - vals:', vals);
          if (vals.length > 0 && vals.every(v => typeof v === 'string' && /^(string|int|integer|float|number|boolean|bool|date|datetime|id|uuid)$/i.test(v))) {
            jsonObj = parsed;
            console.log('✓ Detected as type definitions');
          } else if (vals.length > 0) {
            // Even if not all are type names, treat as nested data structure
            jsonObj = parsed;
            isNestedJSON = true;
            console.log('✓ Treating as nested JSON structure');
          }
        } catch (e2) { 
          console.log('❌ Lenient parse failed:', e2.message.substring(0, 100));
          console.log('Attempted JSON:', normalized.substring(0, 200));
        }
      }
    }

    // Pattern 3: Simple GraphQL-like type (no directives, no enums, no interfaces)
    const hasGraphQLFeatures = /@\w+|^enum\s|^interface\s|^union\s|^input\s|^scalar\s|^extend\s|^schema\s|^directive\s/m.test(trimmed);
    const isGraphQLType = !hasGraphQLFeatures && /^type\s+\w+\s*\{/m.test(trimmed) && !/type\s+(Query|Mutation)\s*\{/m.test(trimmed);

    if (!isSimpleKV && !jsonObj && !isGraphQLType) return null;

    let fields = {};
    let typeName = fallbackServiceName.replace(/API$/i, '') || 'Item';
    let componentSchemas = {};

    const typeMap = {
      'string': 'string', 'int': 'integer', 'integer': 'integer',
      'float': 'number', 'number': 'number', 'boolean': 'boolean', 'bool': 'boolean',
      'date': 'string', 'datetime': 'string', 'id': 'string', 'uuid': 'string',
    };
    const formatMap = {
      'date': 'date', 'datetime': 'date-time', 'id': 'uuid', 'uuid': 'uuid',
    };

    // Helper: infer schema from value
    const inferSchema = (val, keyName = '') => {
      if (typeof val === 'string') {
        const lower = val.toLowerCase();
        if (/^(string|int|integer|float|number|boolean|bool|date|datetime|id|uuid)$/i.test(val)) {
          const schema = { type: typeMap[lower] || 'string' };
          if (formatMap[lower]) schema.format = formatMap[lower];
          return schema;
        }
        // Literal string (e.g., "ncaaf") → enum
        return { type: 'string', enum: [val] };
      }
      if (typeof val === 'number') return { type: 'number' };
      if (typeof val === 'boolean') return { type: 'boolean' };
      if (val === null) return { type: 'string' };
      if (Array.isArray(val)) {
        return {
          type: 'array',
          items: val.length > 0 ? inferSchema(val[0]) : { type: 'string' }
        };
      }
      if (typeof val === 'object') {
        const nestedSchemaName = keyName ? keyName.charAt(0).toUpperCase() + keyName.slice(1) : 'NestedObject';
        const nestedProps = {};
        for (const [k, v] of Object.entries(val)) {
          nestedProps[k] = inferSchema(v, k);
        }
        componentSchemas[nestedSchemaName] = { type: 'object', properties: nestedProps };
        return { $ref: `#/components/schemas/${nestedSchemaName}` };
      }
      return { type: 'string' };
    };

    if (isSimpleKV) {
      // Simple key: type format
      for (const line of simpleLines) {
        const m = line.match(simpleKV);
        if (m) {
          const key = m[1], rawType = m[2].toLowerCase();
          fields[key] = { type: typeMap[rawType] || 'string' };
          if (formatMap[rawType]) fields[key].format = formatMap[rawType];
        }
      }
    } else if (jsonObj) {
      if (isNestedJSON) {
        // Nested JSON structure - infer schema from actual data
        for (const [key, val] of Object.entries(jsonObj)) {
          fields[key] = inferSchema(val, key);
        }
      } else {
        // Flat type definitions
        for (const [key, rawType] of Object.entries(jsonObj)) {
          const rt = rawType.toLowerCase();
          fields[key] = { type: typeMap[rt] || 'string' };
          if (formatMap[rt]) fields[key].format = formatMap[rt];
        }
      }
    } else if (isGraphQLType) {
      const typeMatch = trimmed.match(/type\s+(\w+)\s*\{([^}]+)\}/);
      if (typeMatch) {
        typeName = typeMatch[1];
        const body = typeMatch[2];
        const fieldRe = /(\w+)\s*:\s*(\[?\w+!?\]?)/g;
        let fm;
        while ((fm = fieldRe.exec(body)) !== null) {
          const fname = fm[1];
          let gqlType = fm[2].replace(/[!\[\]]/g, '').toLowerCase();
          const gqlMap = { 'string': 'string', 'int': 'integer', 'float': 'number', 'boolean': 'boolean', 'id': 'string', 'date': 'string', 'datetime': 'string' };
          fields[fname] = { type: gqlMap[gqlType] || 'string' };
          if (gqlType === 'id') fields[fname].format = 'uuid';
          if (gqlType === 'date' || gqlType === 'datetime') fields[fname].format = 'date-time';
          if (fm[2].startsWith('[')) {
            fields[fname] = { type: 'array', items: { type: gqlMap[gqlType] || 'string' } };
          }
        }
      }
    }

    if (Object.keys(fields).length === 0) return null;

    // Add an 'id' field if not present
    if (!fields.id) {
      fields = { id: { type: 'string', format: 'uuid' }, ...fields };
    }

    const svcName = fallbackServiceName || typeName + 'API';
    const pathBase = '/' + typeName.toLowerCase();
    const refSchema = typeName;

    // Build component schemas
    const schemas = {
      [refSchema]: { type: 'object', properties: fields },
      ...componentSchemas
    };

    const openApiSpec = {
      openapi: '3.0.0',
      info: { title: svcName, version: '1.0', description: `Auto-generated CRUD API for ${typeName}` },
      paths: {
        [pathBase]: {
          get: {
            operationId: `getAll${typeName}s`,
            summary: `List all ${typeName}s`,
            responses: { '200': { description: 'OK', content: { 'application/json': { schema: { type: 'array', items: { $ref: `#/components/schemas/${refSchema}` } } } } } },
          },
          post: {
            operationId: `create${typeName}`,
            summary: `Create a new ${typeName}`,
            requestBody: { content: { 'application/json': { schema: { $ref: `#/components/schemas/${refSchema}` } } } },
            responses: { '201': { description: 'Created', content: { 'application/json': { schema: { $ref: `#/components/schemas/${refSchema}` } } } } },
          },
        },
        [`${pathBase}/{id}`]: {
          get: {
            operationId: `get${typeName}ById`,
            summary: `Get ${typeName} by ID`,
            parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
            responses: { '200': { description: 'OK', content: { 'application/json': { schema: { $ref: `#/components/schemas/${refSchema}` } } } } },
          },
          put: {
            operationId: `update${typeName}`,
            summary: `Update ${typeName}`,
            parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
            requestBody: { content: { 'application/json': { schema: { $ref: `#/components/schemas/${refSchema}` } } } },
            responses: { '200': { description: 'OK', content: { 'application/json': { schema: { $ref: `#/components/schemas/${refSchema}` } } } } },
          },
          delete: {
            operationId: `delete${typeName}`,
            summary: `Delete ${typeName}`,
            parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
            responses: { '204': { description: 'Deleted' } },
          },
        },
      },
      components: {
        schemas,
      },
    };

    return { openApiSpec, typeName, serviceName: svcName };
  } catch (err) {
    console.error('detectAndConvertPlainType threw error:', err.message);
    throw err;
  }
}

function convertJsonToOpenAPI(json, serviceName = 'GeneratedAPI') {
  const inferSchema = (obj) => {
    if (Array.isArray(obj)) {
      return {
        type: 'array',
        items: inferSchema(obj[0] || {})
      };
    }

    if (obj !== null && typeof obj === 'object') {
      const properties = {};
      for (const key in obj) {
        properties[key] = inferSchema(obj[key]);
      }
      return { type: 'object', properties };
    }

    if (typeof obj === 'string') return { type: 'string' };
    if (typeof obj === 'number') return { type: 'number' };
    if (typeof obj === 'boolean') return { type: 'boolean' };

    return { type: 'string' };
  };

  const schema = inferSchema(json);

  return {
    openapi: '3.0.0',
    info: {
      title: serviceName,
      version: '1.0.0'
    },
    paths: {
      '/data': {
        get: {
          summary: 'Get data',
          responses: {
            '200': {
              description: 'Successful response',
              content: {
                'application/json': {
                  schema
                }
              }
            }
          }
        }
      }
    }
  };
}

// ── AsyncAPI parsing ────────────────────────────────────────────────

function parseAsyncAPISpec(specText) {
  let spec;
  try {
    spec = JSON.parse(specText);
  } catch (_) {
    spec = yaml.load(specText);
  }
  if (!spec || !spec.asyncapi) throw new Error('Invalid AsyncAPI spec: missing asyncapi version field');

  const serviceName = spec.info?.title || 'AsyncService';
  const serviceVersion = spec.info?.version || '1.0';
  const isV3 = String(spec.asyncapi).startsWith('3');

  const channels = [];

  if (isV3) {
    for (const [channelName, channelDef] of Object.entries(spec.channels || {})) {
      const msg = channelDef.messages ? Object.values(channelDef.messages)[0] : null;
      const payload = msg?.payload || {};
      const examples = (msg?.examples || []).map(ex => ({
        name: ex.name || 'default',
        summary: ex.summary || '',
        payload: ex.payload,
      }));
      channels.push({
        name: channelName,
        description: channelDef.description || '',
        direction: 'publish',
        operationId: channelName,
        messageName: msg?.name || '',
        contentType: msg?.contentType || 'application/json',
        schema: payload,
        examples,
      });
    }
  } else {
    for (const [channelName, channelDef] of Object.entries(spec.channels || {})) {
      const direction = channelDef.subscribe ? 'subscribe' : 'publish';
      const opDef = channelDef.subscribe || channelDef.publish;
      const msg = opDef?.message;
      const payload = msg?.payload || {};
      const examples = (msg?.examples || []).map(ex => ({
        name: ex.name || 'default',
        summary: ex.summary || '',
        payload: ex.payload,
      }));
      channels.push({
        name: channelName,
        description: channelDef.description || '',
        direction,
        operationId: opDef?.operationId || channelName,
        messageName: msg?.name || '',
        contentType: msg?.contentType || 'application/json',
        schema: payload,
        examples,
      });
    }
  }

  // Detect protocol from servers or bindings
  let protocol = 'kafka';
  if (spec.servers) {
    const firstServer = Object.values(spec.servers)[0];
    if (firstServer?.protocol) protocol = firstServer.protocol.toLowerCase();
  }

  return { spec, serviceName, serviceVersion, channels, protocol };
}

function validateAsyncAPISchema(specText) {
  const warnings = [];
  const errors = [];
  try {
    const { spec, channels } = parseAsyncAPISpec(specText);

    if (!spec.info?.title) warnings.push({ type: 'MISSING_TITLE', message: 'AsyncAPI spec has no info.title' });
    if (!spec.info?.version) warnings.push({ type: 'MISSING_VERSION', message: 'AsyncAPI spec has no info.version' });
    if (channels.length === 0) {
      errors.push({ type: 'NO_CHANNELS', message: 'AsyncAPI spec defines no channels' });
    }
    for (const ch of channels) {
      if (!ch.schema || Object.keys(ch.schema).length === 0) {
        warnings.push({ type: 'EMPTY_SCHEMA', message: `Channel '${ch.name}' has no message payload schema` });
      }
    }
    return {
      valid: errors.length === 0,
      errors,
      warnings,
      summary: { channelCount: channels.length, errorCount: errors.length, warningCount: warnings.length },
    };
  } catch (e) {
    return {
      valid: false,
      errors: [{ type: 'PARSE_ERROR', message: `Failed to parse AsyncAPI spec: ${e.message}` }],
      warnings: [],
      summary: { channelCount: 0, errorCount: 1, warningCount: 0 },
    };
  }
}

// ── Protobuf / gRPC parsing ─────────────────────────────────────────

function stripProtoComments(src) {
  const MAX_PROTO_SOURCE_LENGTH = 1_000_000;
  const input = typeof src === 'string' ? src : (Buffer.isBuffer(src) ? src.toString('utf8') : null);
  if (input === null) {
    throw new Error('Protobuf source must be a string');
  }
  if (input.length > MAX_PROTO_SOURCE_LENGTH) {
    throw new Error(`Protobuf source exceeds maximum supported length of ${MAX_PROTO_SOURCE_LENGTH} characters`);
  }

  const out = [];
  let i = 0;
  while (i < input.length) {
    if (input[i] === '/' && input[i + 1] === '/') {
      while (i < input.length && input[i] !== '\n') i++;
    } else if (input[i] === '/' && input[i + 1] === '*') {
      i += 2;
      while (i < input.length && !(input[i] === '*' && input[i + 1] === '/')) i++;
      i += 2;
    } else {
      out.push(input[i]);
      i++;
    }
  }
  return out.join('');
}

function parseProtobufSpec(protoText) {
  const text = stripProtoComments(protoText);

  const syntaxMatch = text.match(/syntax\s*=\s*"(proto\d)"/);
  const syntax = syntaxMatch ? syntaxMatch[1] : 'proto3';

  const packageMatch = text.match(/package\s+([\w.]+)\s*;/);
  const packageName = packageMatch ? packageMatch[1] : '';

  // Microcks extracts version from the last segment of package with 3+ parts
  const pkgParts = packageName.split('.');
  let serviceVersion = '1.0';
  if (pkgParts.length >= 3) {
    const last = pkgParts[pkgParts.length - 1];
    if (/^v\d/.test(last)) serviceVersion = last;
  }

  // Parse messages
  const messages = {};
  const messageRegex = /message\s+(\w+)\s*\{([^}]*(?:\{[^}]*\}[^}]*)*)\}/g;
  let mm;
  while ((mm = messageRegex.exec(text)) !== null) {
    const msgName = mm[1];
    const body = mm[2];
    const fields = {};
    const fieldRegex = /(?:(repeated|optional|required)\s+)?(\w[\w.]*)\s+(\w+)\s*=\s*(\d+)/g;
    let fm;
    while ((fm = fieldRegex.exec(body)) !== null) {
      const modifier = fm[1] || '';
      const fieldType = fm[2];
      const fieldName = fm[3];
      fields[fieldName] = {
        type: fieldType,
        isList: modifier === 'repeated',
        isOptional: modifier === 'optional',
      };
    }
    messages[msgName] = fields;
  }

  // Parse enums
  const enums = {};
  const enumRegex = /enum\s+(\w+)\s*\{([^}]+)\}/g;
  let em;
  while ((em = enumRegex.exec(text)) !== null) {
    const enumName = em[1];
    const valuesStr = em[2];
    const vals = [];
    const valRegex = /(\w+)\s*=\s*\d+/g;
    let vm;
    while ((vm = valRegex.exec(valuesStr)) !== null) vals.push(vm[1]);
    enums[enumName] = vals;
  }

  // Parse services
  const services = [];
  const serviceRegex = /service\s+(\w+)\s*\{([\s\S]*?)\}/g;
  let sm;
  while ((sm = serviceRegex.exec(text)) !== null) {
    const svcName = sm[1];
    const svcBody = sm[2];
    const methods = [];
    const rpcRegex = /rpc\s+(\w+)\s*\(\s*(\w+)\s*\)\s*returns\s*\(\s*(stream\s+)?(\w+)\s*\)/g;
    let rm;
    while ((rm = rpcRegex.exec(svcBody)) !== null) {
      methods.push({
        name: rm[1],
        inputType: rm[2],
        isServerStream: !!rm[3],
        outputType: rm[4],
      });
    }
    services.push({ name: svcName, methods });
  }

  const serviceName = services.length > 0
    ? (packageName ? `${packageName}.${services[0].name}` : services[0].name)
    : packageName || 'GrpcService';

  return { syntax, packageName, serviceName, serviceVersion, messages, enums, services };
}

function validateProtobufSchema(protoText) {
  const warnings = [];
  const errors = [];
  try {
    const parsed = parseProtobufSpec(protoText);

    if (parsed.syntax !== 'proto3' && parsed.syntax !== 'proto2') {
      warnings.push({ type: 'UNKNOWN_SYNTAX', message: `Unknown protobuf syntax: ${parsed.syntax}` });
    }
    if (parsed.services.length === 0) {
      errors.push({ type: 'NO_SERVICE', message: 'Protobuf file defines no service (required for gRPC mocking)' });
    }
    for (const svc of parsed.services) {
      if (svc.methods.length === 0) {
        errors.push({ type: 'NO_METHODS', message: `Service '${svc.name}' defines no rpc methods` });
      }
      for (const method of svc.methods) {
        if (!parsed.messages[method.inputType]) {
          warnings.push({ type: 'MISSING_INPUT', message: `Method '${method.name}' input type '${method.inputType}' not found` });
        }
        if (!parsed.messages[method.outputType]) {
          warnings.push({ type: 'MISSING_OUTPUT', message: `Method '${method.name}' output type '${method.outputType}' not found` });
        }
      }
    }
    return {
      valid: errors.length === 0,
      errors,
      warnings,
      summary: {
        serviceCount: parsed.services.length,
        messageCount: Object.keys(parsed.messages).length,
        errorCount: errors.length,
        warningCount: warnings.length,
      },
    };
  } catch (e) {
    return {
      valid: false,
      errors: [{ type: 'PARSE_ERROR', message: `Failed to parse protobuf: ${e.message}` }],
      warnings: [],
      summary: { serviceCount: 0, messageCount: 0, errorCount: 1, warningCount: 0 },
    };
  }
}

function describeProtoMessage(msgName, messages, enums, depth = 0) {
  if (depth > 4 || !messages[msgName]) return msgName;
  const fields = messages[msgName];
  const lines = Object.entries(fields).map(([fname, info]) => {
    const listPrefix = info.isList ? 'repeated ' : '';
    const typeDesc = messages[info.type]
      ? describeProtoMessage(info.type, messages, enums, depth + 1)
      : (enums[info.type] ? `enum(${enums[info.type].slice(0, 4).join('|')})` : info.type);
    return `  ${'  '.repeat(depth)}${listPrefix}${typeDesc} ${fname}`;
  });
  return `{\n${lines.join('\n')}\n${'  '.repeat(depth)}}`;
}

function describeAsyncChannel(channel) {
  const schema = channel.schema;
  if (!schema || Object.keys(schema).length === 0) return '(no schema)';
  try {
    return JSON.stringify(schema, null, 2).slice(0, 2000);
  } catch (_) {
    return '(schema too complex)';
  }
}

module.exports = {
  detectSchemaType,
  parseGraphQLSchema,
  validateGraphQLSchema,
  cleanSchemaForMocking,
  generateMockViaGraphQLTools,
  parseOpenAPISpec,
  resolveSchemaRef,
  describeSchema,
  detectAndConvertPlainType,
  convertJsonToOpenAPI,
  parseSamplesFromPrompt,
  enhanceSchemaWithAI,
  parseAsyncAPISpec,
  validateAsyncAPISchema,
  parseProtobufSpec,
  validateProtobufSchema,
  describeProtoMessage,
  describeAsyncChannel,
};
